<<<<<<< HEAD
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
=======
baseURL = "https://edcismybrother.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
>>>>>>> d498eae72dedbcc6a501d7457b924a90e2184a76
